/**
 * Push live menu snapshot to GitHub so GitHub Pages stays in sync with admin edits.
 * Requires env: GITHUB_TOKEN (contents:write), optional GITHUB_REPO / GITHUB_BRANCH.
 */

function jsonPretty(value) {
  return `${JSON.stringify(value, null, 2)}\n`;
}

/** Build static files consumed by GitHub Pages + seed. */
export function buildStaticMenuFiles(menu) {
  const sections = Array.isArray(menu?.sections) ? menu.sections : [];
  const items = menu?.items && typeof menu.items === 'object' ? menu.items : {};
  const details = menu?.details && typeof menu.details === 'object' ? menu.details : {};

  const cleanSections = sections.map((sec) => ({
    title: sec.title,
    anchor: sec.anchor ?? null,
    items: (sec.items || []).map((it) => ({
      id: it.id,
      name: it.name,
      price: it.price,
      priceDisplay: it.priceDisplay || `${it.price}тг`,
      img: it.img || 'image/nono.png',
      ...(it.availability ? { availability: it.availability } : {}),
    })),
  }));

  const dataJs = `/* Auto-generated by Friendly admin → GitHub sync. Do not edit by hand. */
window.ITEM_DETAILS = ${jsonPretty(details).trim()};

window.MENU_SECTIONS = ${jsonPretty(cleanSections).trim()};

window.MENU_ITEMS = ${jsonPretty(items).trim()};
`;

  const exportJson = jsonPretty({
    updatedAt: menu?.updatedAt || new Date().toISOString(),
    sections: cleanSections,
    items,
    details,
  });

  return {
    'data.js': dataJs,
    'data/menu-export.json': exportJson,
  };
}

function githubConfigured() {
  const token = (process.env.GITHUB_TOKEN || process.env.GH_TOKEN || '').trim();
  const repo = (process.env.GITHUB_REPO || 'Hmeeti/FriendlyBarMenu1').trim();
  const branch = (process.env.GITHUB_BRANCH || 'main').trim();
  return { ok: Boolean(token && repo), token, repo, branch };
}

async function githubFetch(token, url, init = {}) {
  const res = await fetch(url, {
    ...init,
    headers: {
      Accept: 'application/vnd.github+json',
      Authorization: `Bearer ${token}`,
      'X-GitHub-Api-Version': '2022-11-28',
      ...(init.headers || {}),
    },
  });
  const text = await res.text();
  let body = null;
  try {
    body = text ? JSON.parse(text) : null;
  } catch {
    body = { raw: text };
  }
  if (!res.ok) {
    const msg = body?.message || text || res.statusText;
    const err = new Error(`GitHub ${res.status}: ${msg}`);
    err.status = res.status;
    err.body = body;
    throw err;
  }
  return body;
}

async function getFileSha(token, repo, path, branch) {
  const url = `https://api.github.com/repos/${repo}/contents/${encodeURI(path)}?ref=${encodeURIComponent(branch)}`;
  try {
    const data = await githubFetch(token, url);
    return data?.sha || null;
  } catch (e) {
    if (e.status === 404) return null;
    throw e;
  }
}

async function putFile({ token, repo, branch, path, content, message, sha }) {
  const url = `https://api.github.com/repos/${repo}/contents/${encodeURI(path)}`;
  const body = {
    message,
    content: Buffer.from(content, 'utf8').toString('base64'),
    branch,
  };
  if (sha) body.sha = sha;
  return githubFetch(token, url, {
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body),
  });
}

/** Commit one or more text files to the configured repo/branch. */
export async function pushFilesToGitHub(files, message) {
  const cfg = githubConfigured();
  if (!cfg.ok) {
    return { skipped: true, reason: 'GITHUB_TOKEN not set' };
  }

  const results = [];
  for (const [filePath, content] of Object.entries(files)) {
    const sha = await getFileSha(cfg.token, cfg.repo, filePath, cfg.branch);
    const put = await putFile({
      token: cfg.token,
      repo: cfg.repo,
      branch: cfg.branch,
      path: filePath,
      content,
      message,
      sha,
    });
    results.push({ path: filePath, commit: put?.commit?.sha || null });
  }
  return { ok: true, repo: cfg.repo, branch: cfg.branch, results };
}

/** Push a binary image into the repo (e.g. admin uploads). */
export async function pushBinaryToGitHub(filePath, buffer, message) {
  const cfg = githubConfigured();
  if (!cfg.ok) return { skipped: true, reason: 'GITHUB_TOKEN not set' };
  const sha = await getFileSha(cfg.token, cfg.repo, filePath, cfg.branch);
  const url = `https://api.github.com/repos/${cfg.repo}/contents/${encodeURI(filePath)}`;
  const body = {
    message,
    content: Buffer.from(buffer).toString('base64'),
    branch: cfg.branch,
  };
  if (sha) body.sha = sha;
  const put = await githubFetch(cfg.token, url, {
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body),
  });
  return { ok: true, path: filePath, commit: put?.commit?.sha || null };
}

export function getGitHubSyncStatus() {
  const cfg = githubConfigured();
  return {
    configured: cfg.ok,
    repo: cfg.repo,
    branch: cfg.branch,
  };
}
